### ISSUE TITLE
No mobs spawning on Mob Conveyor

### ISSUE THREAD

**Issue by remclave** [vadis365/Mob-Grinding-Utils#100]
Minecraft Version: 1.12.2
Forge version: 2749
mob_grinding_utils version: 0.3.11

No mobs spawning on Mob Conveyors.

When using F7 to see a spawnable surface, no red or yellow x appears. 

I replaced stone blocks in my manual kill spawner with the Mob Conveyors to automate and the red x'es disappeared.

I already checked to see if this issue was previously reported...

**Comment by vadis365** [comment]
Hello,
The red X's are just a light level check. In extensive testing I had mobs spawning on the block with absolutely no issues and this method in the blocks class means mobs can spawn on it.
https://github.com/vadis365/Mob-Grinding-Utils/blob/MC1.12/MobGrindingUtils/MobGrindingUtils/src/main/java/mob_grinding_utils/blocks/BlockEntityConveyor.java#L54
Cheers,
Me.

**Comment by oliverjanik** [comment]
@vadis365 I think the problem is that conveyor is not a full block. When I stand on it I sink in a bit I don't think it has full 1m height.

I'm getting 0 mob spawns

**Comment by psouza4** [comment]
Same issue here, @vadis365 -- nothing spawns on these blocks.  I swapped out cobblestone with fans for conveyors and it halted all mob spawning entirely.  Appreciate your work -- would love to see a fix for these blocks!

**Comment by StarmanOmega** [comment]
This is a definite problem, an hour of idling with only these blocks as spawn tiles yeild no results. It's most likely due to the block not really being a full block, as mentioned by oliverjanik. 
![stoneblock version 1 0 20 mob_grinding_utils problem](https://user-images.githubusercontent.com/44080215/46848930-a7586780-cdba-11e8-9908-a3db9051af49.png)
