### ISSUE TITLE
Absorption hopper crash

### ISSUE THREAD

**Issue by hoeglse** [vadis365/Mob-Grinding-Utils#115]
* **Modpack Version**:  mob_grinding_utils 0.3.13 modpack stoneblock 2 1.7.0
* **Issue**: Absorption Hopper next to a cyclic energy transfernode. If you chance the connection between hopper and transfernode to fluid the game crash.

* **Link to Log or Crash File Paste**:
  Crash ingame: https://paste.dimdev.org/ipazutuvoh.mccrash

Loading world: https://paste.dimdev.org/rigenazofa.mccrash

* **Is it Repeatable?**: Yes
* **Mod/s Affected**: mob_grind_utils and cyclic
* **Known Fix**: Load world with mcedit and remove the connection to cyclic energy transfernode

**Comment by vadis365** [comment]
Hello,
This issue is an odd one ;)
I'll have a chat with Loth (Cyclic dev) and see what he thinks.
I would suggest connecting the AH to a buffer block 1st and then going from that if there are issues here.
The AH can push fluids and items out without the need for other blocks, infact a lot of pipes bottle neck it as it can push from all of it's inventory slots in to a chest rather than 1 thing at a time.
Cheers,
Me.

**Comment by vadis365** [comment]
Hello,
Looks like some issues with capability checking is causing this. I have spoken to Loth and it looks like we can make them play nice. Should be sorted soon. 
Cheers,
Me.
