### ISSUE TITLE
Tap issue

### ISSUE THREAD

**Issue by fbsukita** [vadis365/Mob-Grinding-Utils#151]
i'm having problems to use the tap to get xp, when i place the tap it is always facing the same side and when i try to turn it on it makes the animation and the sound but don't work

**Comment by fbsukita** [comment]
![1](https://user-images.githubusercontent.com/21989837/115941302-35793280-a47b-11eb-8f15-ffdadcb366df.png)
![2](https://user-images.githubusercontent.com/21989837/115941305-38742300-a47b-11eb-90cf-280ca792d773.png)

**Comment by fbsukita** [comment]
i've tried with the 0.4.21 version too and it is having the same problem

**Comment by fbsukita** [comment]
![3](https://user-images.githubusercontent.com/21989837/115941632-8dfcff80-a47c-11eb-8ea8-4d8f2cd9a310.png)

**Comment by vadis365** [comment]
Hello,
I have tried to duplicate this and can't. I'm not sure what your issue is here, but it may be a weird mod interaction with perhaps optifine.
I can place the taps correctly on several tanks, and others have also been able to use them as intended (including live streams of the mod being used in a pack).
I'm not really sure what the issue is and I can't repeat it, and no one else I have asked can.
I'd suggest removing optifine, testing, and reporting back.
Cheers,
Me.

**Comment by fbsukita** [comment]
i've tried whitout the optfine but the problem stands

**Comment by fbsukita** [comment]
i've discoverd the source of the problem, it's needed to press "shift" to place the tap
