### ISSUE TITLE
Zombie Reinforcements

### ISSUE THREAD

**Issue by malianx** [vadis365/Mob-Grinding-Utils#19]
The mob masher triggers zombie reinforcement spawns, other mob killing blocks like the killer joe do not do this.

**Comment by vadis365** [comment]
Hello,
I don't really see this as an issue tbh. The Mob Masher uses the exact same fake player mechanics as any other mod, the only difference I guess may be that the masher uses an imaginary sword to kill mobs.
I would suggest making sure your mob farms are enclosed and this won't be a problem.
Cheers,
Me.

**Comment by TheCyberBrick** [comment]
You could register a listener for SummonAidEvent and set result to DENY if the attacker == fake player

**Comment by malianx** [comment]
Punji sticks don't cause this effect, killer joe doesn't cause this effect, diamond spikes don't cause this effect. Obviously there is something different for them, possibly the above suggestion.

I've tested this on half a dozen fully enclosed boxes.

The zombie reinforcement mechanic doesn't care about lighting or solid blocks, it will spawn on any surface within about 62m of the event.

If you don't want the masher to be usable on hard, that's fine, but that's how it is right now.

**Comment by vadis365** [comment]
Hello,
Punji sticks are not the same. We can easily turn the event off as @TheCyberBrick has said - it's pretty easy to do. Mob Grinding Utils was originally made for the Sky Factory 3 mod pack and I guess the lack of space on a skyblock world means this hasn't cropped up as an issue for people before now. As for the Mob Masher not being usable on hard mode due to this one thing - haha you obviously are feeling a little salty for some reason. We do appreciate the report as it will help us to improve the mod and tweak things. I'll re-open this issue so when the next release is pushed out we may have this done.

"...that's fine, but that's how it is right now.

Cheers,
Me.

**Comment by malianx** [comment]
No rather, the implication is that it's only an issue on Hard, because the reinforcement chance is either zero or very very small on normal, but on Hard its very very often. As it stands, even a smallish box (9x9) will end up with zombies outside it every few minutes, sometimes as far as 40-50 blocks away, on a different floor of a tower for example. That makes it basically unusable on that mode, unless you like your living space full of zombies at random.

I pointed out the discrepancy in case that's something you do intend, the gap between difficulties. And I'm aware the vast majority of players/servers operate on normal.

**Comment by vadis365** [comment]
Hello, 
Honestly - it was something I didn't account for when making the mod - but now you have pointed it out I can see how it could be quite hectic in a mob farm where the frequency of zombie kills would be higher than just normal player kills. It'll get changed - don't worry. ;)
Cheers,
Me.

**Comment by vadis365** [comment]
should be all good ;)
