### ISSUE TITLE
Radius upgrade for absorption hopper

### ISSUE THREAD

**Issue by calog3no** [vadis365/Mob-Grinding-Utils#20]
When I place the upgrades in the slot in the gui on right hand side they get pulled out like it is an item

**Comment by fuelhauler** [comment]
Same. I've had them pulled and placed into any available (non-locked storage drawer, for example) inventory. I've also had them pulled out of one hopper and placed into the output inventory of another while I was troubleshooting the problem and had switched the Item Conduit to Extract and Insert.

**Comment by vadis365** [comment]
Hello,
This is a known issue atm - it didn't happen until the last version or so due to us having to update some code for the new way forge handles cross mod inventory capabilities. For the time being, if you can, I would add a filter and black list the hopper upgrade for conduits etc. I will get a fix for this in a coming update as it will involve a bit of custom code to fix.
Cheers,
Me.

**Comment by vadis365** [comment]
may be fixed now - closing for now will re-open if it's still borked.
updating the mod ready for a release (hopefully within the hour)
