### ISSUE TITLE
tags/entitytype question

### ISSUE THREAD

**Issue by sharkweekthings** [vadis365/Mob-Grinding-Utils#302]
Forge 1.20.1
mob_grinding_utils-1.20.1-1.1.0.jar

I was looking to disable  a few mobs from the Dreadful Dirt spawn and the tags/entitytypes folder is throwing me off a bit. Things look like they would be self explanatory, but I want to double check.

No Delightful Spawn - pretty easy, mobs here won't spawn on delightful dirt
No Dreadful Spawn - also should be easy, mobs wont spawn on dreadful dirt

then you have "no spawn" and "no dirt spawn". 

Does "no spawn" prevent mobs from spawning anywhere in the world, and no dirt spawn prevents mobs from spawning on minecraft:dirt block? 

So for the base of the mod, you are allowing Centipedes and Farseers to spawn inside of the dreadful dirt, but you are blocking them from spawning on other dirt in the "no_dirt_spawn"? 

I feel like that's backwards. 

I've always had issues with Farseers and Centipedes inside a mob farm, so I would block them from the dreadful dirt spawn, but I didn't want to eliminate them from the game entirely. 

If that's the case, would I need to change Farseer and Centipede to be blocked in the "no_dreadful_dirt" json, and remove them from the "no_dirt_spawn" json? which would block them from dreadful dirt, but allow them on normal dirt?

**Comment by Flanks255** [comment]
Ah sorry for the delay, didnt see this till just now.

you are correct on the dreadful/delightful tags, no dirt is just a combo of both of them, IE it blocks from both dirt types, mainly cause it came first, and later i split it up.

"no spawn" relates to the mob spawner machine.

so both of those mobs are blocked from the 2 spawner dirts. (because i added the tag to them before i split it.)

**Comment by sharkweekthings** [comment]
Thank you for the clarification on that :)
