### ISSUE TITLE
Usage of FluidStack data component causes tanks to be unable to be extracted from Refined Storage

### ISSUE THREAD

**Issue by raoulvdberge** [vadis365/Mob-Grinding-Utils#311]
Hello there,

`FluidStack` does not implement equals and/or hashcode. 

If you try to insert a XP Drain Singulary Tank into Refined Storage, and then try to extract it, the extraction will fail because:
- Refined Storage will send an example stack to be extracted to the server
- It will reconstruct the stack based on item ID and data component map
- It will try to extract this *exact* stack from storage.

However, if the object identity is not stable due to missing equals and/or hashcode, this extraction for the *exact* stack will fail. 

My suggestion is to use a wrapper object that implements equals/hashcode correctly for the data component.

* Ref: https://github.com/refinedmods/refinedstorage2/issues/754
* Ref: https://github.com/vadis365/Mob-Grinding-Utils/blob/MC1.21/MobGrindingUtils/MobGrindingUtils/src/main/java/mob_grinding_utils/components/MGUComponents.java#L24

**Comment by Flanks255** [comment]
Interesting, i forgot all about this, when i tried to do something similar in Actually Additions, I HAD to make a wrapping object because it didn't function at all because of the same issue lol, how i got away with this in MGU but not AA i do not know...
At least i can just copy the other class i wrote haha.

**Comment by Flanks255** [comment]
Fixed in next build.
