### ISSUE TITLE
Crash with Hatchery

### ISSUE THREAD

**Issue by BrisingrAerowing** [vadis365/Mob-Grinding-Utils#38]
I randomly used a GMO Chicken Feed on a Hatchery Rooster, and got a crash that prevents loading the world again.

[Crash Log](https://gist.github.com/BrisingrAerowing/dc3ea9d0e78a785b083ff884843e4cd0)

Adding a check for the correct model type would help.

**Comment by vadis365** [comment]
Hello,
Thanks for the report - I actually made the Rooster for Hatchery so I'm familiar with the code.
I will just prevent MGU from interacting with the rooster as the model doesn't extend the chicken model at all it is just crashing the renderer. Sorry about your world, have you tried to remove the rooster mob with World Edit? - that may allow you to use it once more. This will be fixed in the next update.
Cheers,
Me.

**Comment by vadis365** [comment]
Should be fixed in the next update out this week.

**Comment by BrisingrAerowing** [comment]
I couldn't even load the world with MCEdit, the program complained about corrupted data. I think the game was in the middle of writing data to disk when the crash happened, as the level.dat size was only 1K.

I only had about 15 minutes of playtime on the world (in creative), so it was no big deal. The seed wasn't all that interesting either (a lot of ocean with a few tiny islands. I had not seen any major landmasses at all while flying in the same direction for about 14 minutes, then I found an island with a rooster and some chickens, and then the crash at that point)
