### ISSUE TITLE
XP dupe is back

### ISSUE THREAD

**Issue by InThayne** [vadis365/Mob-Grinding-Utils#50]
Same as previous issues with xp duplication- 
     In this case xp tap, singularity tank and EnderIO experience rod.

FTB Beyond modpack
M_G_U version 0.1.8.21

**Comment by vadis365** [comment]
idk.
This has been fixed and the code hasn't been touched since. I'm no longer going to attempt to correct the mod interaction with EndeIO's xp duplication wand. I'm sorry, but I have no idea why this is happening again. If it is a game breaking problem, I would suggest just not using Mob Grinding Utils and just use EnderIO blocks, as it is a much better mod and does everything you need.

**Comment by InThayne** [comment]
Sorry, didn't mean to sound pretentious.  My granddaughter found it actually and is respecting my wishes not to exploit it.  All is good with your mod from our perspective.  Just thought a heads up was in order (maybe more so for future expert versions). 

Regards

**Comment by vadis365** [comment]
Hello,
No need to apologise - I'm the one who should be sorry - I didn't mean to sound so unhelpful, I'll take another look at the code when I can get a chance and see if I can figure out what the issue is this time.
Thanks for the report.
Cheers,
Me.
