### ISSUE TITLE
License/Modpack policy

### ISSUE THREAD

**Issue by UnPure** [vadis365/Mob-Grinding-Utils#56]
Hey there.
I'm currently working on a small modpack and i would like to add mob_grinding_utils to it.
I cant find any informations about your modpack policy or a license about your mod.
Do you allow your mod to be part of modpacks?
If yes, could you add a small part of text to the curseforge page?

**Comment by UnPure** [comment]
Sure, but if i want to use other launchers (like the ftb launcher for exmaple) its always nice to know if i'm allowed to do that. ;)

**Comment by UnPure** [comment]
Closing without any answer from the dev? Thanks!

**Comment by vadis365** [comment]
Hello,
No need to get all shirty and entitled - The issue was closed because you have an answer from another dev who has explained how it works - why should I duplicate his answer? If you read the terms of service for the publication of modpacks on the curseforge/twitch pages, you will see that use of mods with the twitch launcher is actually part of it. However if you ask me nicely if it can be included in a public pack - I would probably say yes, as long as a link to the curseforge for the mod is added somewhere, you are not making any financial reward, and you are not redistributing or hosting the mod on any other sites.
Me.

**Comment by vadis365** [comment]
Re-opened because this person need something explained in more detail. 
BUT also closing it again because I like to annoy people who make sarcastic remarks!

**Comment by UnPure** [comment]
Oh you like spam? Good thing i have no time now ;)
