### ISSUE TITLE
Mob Masher Upgrades Disappearing when used with EnderIO Redstone Conduits

### ISSUE THREAD

**Issue by Liammail7** [vadis365/Mob-Grinding-Utils#97]
Using a mob masher with 10 beheading upgrades and 10 fortune upgrades for wither farm and they randomly despawn out of the mob masher

**Comment by bbf** [comment]
I'm also having the same issue.  Whenever there's a server restart, all the upgrades from the masher disappear.

@vadis365 are you serializing the container in the Tile Entity NBT? Because I loaded up a chunk with NBTExplorer, and there's nothing on the TE section that would suggest it's being saved there. I also took a peek at the source, and I don't see any special handling of the container contents, so I'm wondering if that has even been implemented.

**Comment by vadis365** [comment]
Hello,
Considering this is the 1st time this has been reported and as such is a new issue, I'm not sure why it's suddenly happening. The Tile NBT is saved as it has always been; it implements a basic inventory and the contents are saved in the TE's read and write to NBT methods. I'll do some testing, but this is strange.
Cheers,
Me.

**Comment by ET2Fry** [comment]
I did a little more investigation.  I have one masher for a week powered by a lever it has never lost the upgrades.  Another room has 7 mashers powered by ender IO redstone conduit 4 of the 7 lost the upgrades.  I replaced ender IO conduit with switches and all 7 kept the upgrades after a restart.  Could it be an issue between ender IO redstone conduit and the masher?

**Comment by HenryLoenwind** [comment]
Reminds me of issues with disappearing paint some people have. There, however, it only happens when making the network packets, not when writing the save.

Preliminary diagnosis: Some TileEntity is crashing when writing NBT and Forge is silently eating the crash, but stopping the chunk's serializing completely.

**Comment by vadis365** [comment]
I have just spotted some legacy code in some of the TE's in MGU that are returning null stacks on methods concerning the inventory eg. public ItemStack removeStackFromSlot(int slot) is returning null rather than an empty stack or being handled in other ways - I'll fix this and push a new build in a few hours time. This is probably not connected with the above issue, but is a concern that it has been missed for so long - doh!

**Comment by bbf** [comment]
@HenryLoenwind / @vadis365 Would attaching a debugger, making a change to the TE and running /save-all with an Exception catchall breakpoint possibly catch the issue? I never tried a broad Exception breakpoint in Minecraft and I'm afraid that I might see things that cannot be unseen.

**Comment by HenryLoenwind** [comment]
I think that may actually work. Good idea.

**Comment by HenryLoenwind** [comment]
ok, when saving TEs into the save file, exceptions are caught and logged:

![image](https://user-images.githubusercontent.com/1485873/43922691-bc0e1be2-9c1f-11e8-8997-b7c9b83879dc.png)

So if anything goes AWOL from saving+loading it must be the block's own fault.

On the server->client syncing there is no try{}catch block. So actually any error there should kill the server, it seems?

Now that leaves me a bit puzzled as I fail to see any way of TE data getting dropped without a log message. Aside from some mod manually deleting the TileEntity, but that is not a common practice as it is utterly useless.

**Comment by vadis365** [comment]
EnderIO redstone conduits are the issue here.

**Comment by HenryLoenwind** [comment]
I didn't say that it's not the conduits, I said that I don't see how this can happen without any message in the logfile.

**Comment by vadis365** [comment]
That sounded a like I was blaming you @HenryLoenwind - my apologies.
What I meant to say is; the conduits have an issue with MGU and I'll see if other mods do too, as I'm not ruling it out as an issue with MGU itself.
More stack checks in MGU are wrong which shows the codebase to be a little neglected. I'm still surprised they have gone for so long un-noticed and not cropped up as issues sooner.

**Comment by HenryLoenwind** [comment]
np, I got a bit into the habit of triple-stating things in github tickets as there are more and more people around that mis-read even simple statements... ;)

**Comment by vadis365** [comment]
are these still a thing in the latest version?
enderio:blockEndermanSkull

**Comment by HenryLoenwind** [comment]
The skulls are still there, but the id is under_score_case nowadays (block_enderman_skull).

Registries are easy to find...if you know how. Otherwise it really is a bit hard. Every sub-project has a "...Object" class in its "init" package. (or just look what "implements IModObject"). There all the blocks and items are in.

**Comment by vadis365** [comment]
ta - that is al lI needed ;)

**Comment by notcake** [comment]
I'm experiencing this issue too.

I have mob mashers and fans both connected to redstone conduit and only the mashers are losing their upgrades and glitching out.

I'm not familiar with Minecraft modding but `BlockSaw.setState` (called from `neighborChanged`) looks really suspicious:
https://github.com/vadis365/Mob-Grinding-Utils/blob/MC1.12/MobGrindingUtils/MobGrindingUtils/src/main/java/mob_grinding_utils/blocks/BlockSaw.java#L130
Either this code can `NullPointerException` or the null check below is redundant. The `world.setTileEntity` call also looks redundant(?).

Fans handle active state entirely differently (why??): `TileEntityFan.setActive` is never called and the `active` field is never used. There's also no corresponding `BlockFan.setState` method.

**Comment by HenryLoenwind** [comment]
um, you should never call `world.setTileEntity()` with a TE you got from `world.getTileEnitity()`. It may be called "set" but it doesn't replace the existing one, so it is only save to use after a `setBlockState()`. Otherwise you end up having your TE in the TE lists multiple times...

**Comment by vadis365** [comment]
Pushed 0.3.13 update to curse (awaiting approval)

**Comment by notcake** [comment]
Thanks for making the new release. This bug appears to be fixed now:

I restarted my server 3 times on 0.3.11 and my mob mashers glitched and lost their upgrades each time.
I did the same thing 3 times on 0.3.13 and my mob mashers did not lose their upgrades at all.

**Comment by vadis365** [comment]
Hello,
Fantastic news. Looks like we squashed another bug... for now :)
Thanks for taking the time to report your findings.
I'm going to close this for now and tag @HenryLoenwind - just to say thanks for the help on tracking stuff down.
Cheers,
Me.
